apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- behavior: replace
  files:
  - ./supergraph.graphql
  name: supergraph
resources:
- ../base
images:
- name: prasek/supergraph-router:latest
  newName: prasek/supergraph-router
  newTag: 1.1.6
