apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
images:
- name: prasek/subgraph-inventory:latest
  newName: prasek/subgraph-inventory
  newTag: 1.1.12
- name: prasek/subgraph-products:latest
  newName: prasek/subgraph-products
  newTag: 1.1.7
- name: prasek/subgraph-users:latest
  newName: prasek/subgraph-users
  newTag: 1.1.11
